### ISSUE TITLE
improve docs how to add/use (big) raster files in Input

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/docs#103]
https://docs.google.com/document/d/15mtmGiVDYmi4V3p_y5yZUZhGEi5Np_smE5Tegsl3OMg/edit

**Comment by wonder-sk** [comment]
@lieti may have some suggestions and/or experience to share :)

**Comment by lieti** [comment]
Still actual? I was without internet connection for last month.

**Comment by PeterPetrik** [comment]
yep
