### ISSUE TITLE
Use project extent instead of WMS extent ...

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/docs#109]
This page:
https://merginmaps.com/docs/tutorials/further-project-customisation/#project-extent
should be updated to use project extent:
https://github.com/lutraconsulting/input/pull/1762

**Comment by wonder-sk** [comment]
maybe not very clear from pull requests where is the right place where project extent can be set, it's here:

![image](https://user-images.githubusercontent.com/193367/157701083-dc03cd8c-98ca-4be4-bc4f-563fc391af3b.png)
