### ISSUE TITLE
stake out - update screenshots

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/docs#126]
Replace screenshots in /docs/field/stake-out/ when https://github.com/lutraconsulting/input/issues/1948 is resolved.

**Comment by PeterPetrik** [comment]
should be fixed in input 1.4.0

**Comment by PeterPetrik** [comment]
similarly to https://github.com/MerginMaps/docs/issues/48 , we may want to wait until second half of May so we do not need to do it twice
