### ISSUE TITLE
Document plugin reporting tool

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/docs#134]
- you need to go to web-browser and check which versions to use:
- you can only use CSV for output
- you need to select folder ATM

new processing tool:
<img width="782" alt="Screenshot 2022-03-21 at 9 08 18" src="https://user-images.githubusercontent.com/804608/159225343-4f40daef-246c-41fe-88f1-9dab467b13c0.png">

result is no-geom table with the diffs:
<img width="916" alt="Screenshot 2022-03-21 at 9 08 48" src="https://user-images.githubusercontent.com/804608/159225370-d5941b36-1a4d-4b93-b76b-c9b26c67d5a0.png">

see
https://github.com/lutraconsulting/qgis-mergin-plugin/pull/343

**Comment by PeterPetrik** [comment]
released yesterday

**Comment by PeterPetrik** [comment]
update to the tool going out next week

**Comment by alex-cit** [comment]
also "Create diff" and "Extract local changes"
