### ISSUE TITLE
A guide to share large background offline back between multiple projects

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/docs#137]
See this:
https://github.com/lutraconsulting/input/issues/2002#issuecomment-1076298421

**Comment by PeterPetrik** [comment]
related to https://github.com/MerginMaps/docs/issues/103

**Comment by saberraz** [comment]
I had a quick draft for a support query, @alex-cit maybe you can polish it and use it for the documentation.Note that this is only possible for Android atm.

- Create 2 folders:
​ - In the first folder, place the aerial photos, large vectors and rasters, etc.
 - In the 2nd folder, create a QGIS project and place your survey layer there within that folder. 
 - Load the background layers from the first folder in the QGIS project (located in the 2nd folder).
​ - Move the 1st folder to tablet in the app project folder (https://merginmaps.com/docs/manage/missing-data/#manual-data-transfer-android).
​
The 2nd folder will contain your Mergin Maps project. You can use the Mergin Maps plugin to transfer the data to the device. Make sure to use the Wizard and select the last option for uploading a project as is.
​
QGIS uses relative path to load the data. So, the QGIS project uploaded through Mergin Maps will be able to find the background layers side loaded. Users can still work offline and sync the data on the MM project for their survey and the background maps will not be touched.
