### ISSUE TITLE
Add information to exclude a field to be used in Search

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/docs#146]
Under https://merginmaps.com/docs/gis/search_data/ we should add a section on how to exclude a column in the search:
![image](https://user-images.githubusercontent.com/2649047/162398176-f9827bdf-61e6-48a3-8a0d-85d53e0ef1e6.png)

**Comment by PeterPetrik** [comment]
maybe cleanup/merge with https://merginmaps.com/docs/gis/enable_browsing/
