### ISSUE TITLE
Update the cascade form

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/docs#16]
https://github.com/lutraconsulting/input-docs/pull/44

**Comment by PeterPetrik** [comment]
@saberraz can you please send a screenshot/mergin project or something to understand the requirements? thanks

**Comment by saberraz** [comment]
@PeterPetrik there is no screenshots. The page was updated to include more texts and images for users to understand what drill-down forms are and how they are set up.

It is just copy and paste the new contents added in the PR to the new website.

**Comment by PeterPetrik** [comment]
Ok, I think now I undertand. It is about applying PR in the old doc https://github.com/lutraconsulting/input-docs/commit/480131a40d7fdf22829c83903d0daff98ab049fb to this repository, because it was not ported.
