### ISSUE TITLE
exif sample project

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/docs#206]
[Exif metadata](https://merginmaps.com/docs/layer/exif_metadata/) refers to [lutraconsulting/test_exif ](https://app.merginmaps.com/projects/lutraconsulting/test_exif/tree) project. This project should be moved to "documentation".

Default values used in this project (using read_exif() function) display an error - the function is not known.
![image](https://user-images.githubusercontent.com/94905350/181812869-34ba921a-f5df-4735-a457-a246d1c7722c.png)

**Comment by PeterPetrik** [comment]
isn't `read_exif` function only available on Input App? in that case I am not sure of preview on desktop would work, since QGIS desktop may know know about it (@wonder-sk ?) if that is the case, it is not an error, but we can warn user that this is perfectly ok
