### ISSUE TITLE
Add a page about configuration of external links

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/docs#21]
How to set up project so that user can click on some link that will lead to a browser.

Bonus points for opening link to a navigation app, e.g. google maps

https://github.com/lutraconsulting/input-docs/issues/49

**Comment by PeterPetrik** [comment]
One needs to use Text Widget with Multiline and HTML and HTML link: '<a href="https://en.wikipedia.org/wiki/Salzburg">Link text</a>'

If link should be changed based on the different attribute and changed accordingly (e.g. part of the link URL is value of different field), one needs to use default value set with setting of 'Apply default value on update'. 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/804608/159215672-a37b7fb9-57ca-4307-9e7e-14eb981b040f.png">
