### ISSUE TITLE
update subscriptions

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/docs#295]
with upcoming changes in subscription plans, pages where they are mentioned will need to be updated:

- [x] https://merginmaps.com/docs/setup/subscriptions/ 
- [x] https://merginmaps.com/docs/manage/dashboard/ - Maps (beta), Subscription tab
- [x] https://merginmaps.com/docs/manage/workspaces/ 
- [x] https://merginmaps.com/docs/setup/sign-up-to-mergin-maps/ - tip mentions free subscription

**Comment by PeterPetrik** [comment]
also it would be good to add labels/notes to API and WebMaps in docs so it is clear to users when it is possible to use 
- API (REST-api, db-sync, media-sync, workpackages, mergin-py-client, mergin-cpp-client) is possible to use in Trial, Educational, NGO, Team subscription and in CE+EE. FORBIDDEN in Individual and Pro subscriptions
- WebMaps - detto

**Comment by tomasMizera** [comment]
+ write "how to cancel subscription" subpage
+ webmaps https://merginmaps.com/docs/manage/dashboard/#:~:text=MAP%20(beta)%20contains%20the%20map%20overview%20of%20the%20project.%20It,. change to only team subs
