### ISSUE TITLE
Altitude is orthometric

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/docs#324]
https://merginmaps.com/docs/field/input_ui/ states that "Altitude: ellipsoidal height"

At least when external GNSS is used, the altitude is orthometric (as reported in GGA NMEA sentence).

It would be good to check if the internal GPS of android/ios also report orthometric heights or ellipsoid heights.

**Comment by alex-cit** [comment]
@tomasMizera could you please check how it works with internal GPS?

**Comment by tomasMizera** [comment]
https://developer.android.com/reference/android/location/Location#getAltitude()

**Comment by tomasMizera** [comment]
`The altitude of this location in meters above the WGS84 reference ellipsoid.`

**Comment by wonder-sk** [comment]
Also see https://github.com/MerginMaps/input/issues/2615#issuecomment-1645425322
