### ISSUE TITLE
Improve 1-N relations

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/docs#342]
1-N relations should be explained in more detail to make it easier to understand and use in Mergin Maps

Right now, we have two pages regarding 1-N relations:
https://merginmaps.com/docs/layer/one-to-n-relations/
https://merginmaps.com/docs/layer/attach-multiple-photos-to-features/

**Comment by tomasMizera** [comment]
Let's close this for now, we can reopen if there will be something actionable
