### ISSUE TITLE
Top-level sections need better split

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/docs#37]
Right now we have 1. Home, 2. Get started, 3. Concepts, 4. How to, 5. Reference

The "How to" section has a long list of pages, with a lot of content mixed up. It would be good to further split it up to, e.g.:
- pages only related to Input
- pages only related to QGIS plugin
- pages only related to web interface
- general how-to pages (?)

**Comment by PeterPetrik** [comment]
we have discussed it with Pete, splitting "how-to" could lead to less clear documentation. And usually in "how-to" you get by googling, not by going there via menu. I think once we cleanup existing how-to pages (which are copied from old docs), we can revisit the menu (some of how-to could be reference or guides, so at the end we may end up with less how-tos"
