### ISSUE TITLE
Dashboard redesign

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/docs#436]
Due to the redesgin of the dashboard, we will need to update the pics in the docs:

**Tutorials**
- [x]  https://merginmaps.com/docs/tutorials/working-collaboratively/

**Install & Sign Up**
- [x]  https://merginmaps.com/docs/setup/sign-up-to-mergin-maps/

**Manage Account & Project**
- [x] https://merginmaps.com/docs/manage/workspaces/
- [x] https://merginmaps.com/docs/manage/subscriptions/
- [x] https://merginmaps.com/docs/manage/permissions/
- [x] https://merginmaps.com/docs/manage/create-project/#create-a-project-through-merginmaps-com
- [x] https://merginmaps.com/docs/manage/project-advanced/
- [x] https://merginmaps.com/docs/manage/delete-files/
- [x] https://merginmaps.com/docs/manage/dashboard/
- [x] https://merginmaps.com/docs/manage/project-details/

**Support & Legal**
- [x] https://merginmaps.com/docs/misc/troubleshoot/

**Comment by PeterPetrik** [comment]
released 26-03-2024
