### ISSUE TITLE
Mobile app redesign

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/docs#437]
Due to the redesgin of the mobile app, we will need to update the pics in the docs:

**Tutorials**

- [x] https://merginmaps.com/docs/tutorials/capturing-first-data/
- [x] https://merginmaps.com/docs/tutorials/opening-surveyed-data-on-your-computer/
- [x] https://merginmaps.com/docs/tutorials/creating-a-project-in-qgis/#configure-attributes-forms (form preview)
- [x] https://merginmaps.com/docs/tutorials/mobile/
- [x] https://merginmaps.com/docs/tutorials/further-project-customisation/

**Install & Sign Up**

- [x] https://merginmaps.com/docs/setup/install-mobile-app/
- [x] https://merginmaps.com/docs/setup/sign-up-to-mergin-maps/#from-mergin-maps-mobile-app

**Manage Account & Project**

- [x] https://merginmaps.com/docs/manage/workspaces/#switch-workspaces-in-mergin-maps-mobile-app
- [x] https://merginmaps.com/docs/manage/create-project/#create-a-project-in-mergin-maps-mobile-app
- [x] https://merginmaps.com/docs/manage/plugin-multi-server-use/#custom-server-configuration-in-mergin-maps-mobile-app

**Setup GIS Project**
- [x] https://merginmaps.com/docs/gis/features/#image (form preview)
- [x] https://merginmaps.com/docs/gis/search_data/
- [x] https://merginmaps.com/docs/gis/setup_themes/#map-themes-in-mergin-maps-mobile-app
- [x] https://merginmaps.com/docs/gis/snapping/
- [x] https://merginmaps.com/docs/gis/proj/

**Configure Survey Layer**
- [x] https://merginmaps.com/docs/layer/settingup_forms/
- [x] https://merginmaps.com/docs/layer/settingup_forms_settings/
- [x] https://merginmaps.com/docs/layer/form-layout/
- [x] https://merginmaps.com/docs/layer/exif_metadata/
- [x] https://merginmaps.com/docs/layer/settingup_forms_photo/#photos-in-mergin-maps-mobile-app
- [x] https://merginmaps.com/docs/layer/attach-multiple-photos-to-features/
- [x] https://merginmaps.com/docs/layer/one-to-n-relations/
- [x] https://merginmaps.com/docs/layer/external-link/
- [x] https://merginmaps.com/docs/layer/working_with_nonspatial_data/

**Fieldwork Tips**
- [x] https://merginmaps.com/docs/field/input_ui/
- [x] https://merginmaps.com/docs/field/external_gps/
- [x] https://merginmaps.com/docs/field/gps_accuracy/
- [x] https://merginmaps.com/docs/field/tracking/#using-position-tracking-in-mergin-maps-mobile-app
- [x] https://merginmaps.com/docs/field/autosync/
- [x] https://merginmaps.com/docs/field/layers/
- [x] https://merginmaps.com/docs/field/input_features/
- [x] https://merginmaps.com/docs/field/reuse-last-values/
- [x] https://merginmaps.com/docs/field/stake-out/
- [x] https://merginmaps.com/docs/field/broken-project/

**Support & Legal**
- [x] https://merginmaps.com/docs/misc/troubleshoot/#diagnostic-log-on-mergin-maps-mobile-app

**Comment by PeterPetrik** [comment]
also bear in mind that the demo projects are deleted and on clean start you need to create first project yourself
