### ISSUE TITLE
Contribute page: wrong links

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/docs#44]
https://merginmaps.com/docs/howto/contribute/

Links to "Mergin Maps Field Input" and "Mergin Maps Cloud" are repeated multiple times but leading to different places.

Also, it should read "Mergin Maps Input" instead of "Mergin Maps Field Input" ..?

![image](https://user-images.githubusercontent.com/193367/144914039-426104c6-563b-44ae-976f-df0cee6cd399.png)

**Comment by PeterPetrik** [comment]
I think I fixed this alrready on dev during refactoring
