### ISSUE TITLE
Garmin GPSMAP 65S - Bluetooth - Please, add compatibility

### ISSUE THREAD

**Issue by rbperezu1980** [MerginMaps/docs#496]
Hi, Why isn't possible link Garmin GPSMAP 65S using  Bluetooth way  to have more accurrace precision on my tablet? I was reading the supperted devices and not include Garmin. But, Why? Could you think include this supported in your updates? Thanks, excellent app.

**Comment by tomasMizera** [comment]
Hi @rbperezu1980, we add devices that we or our customers tried out and worked. This list is not exhaustive so if you managed to us this device, we can add it there. Just let us know whether it worked via Mock location or directly via Bluetooth from Mergin Maps. I understand that you speak about Android and not iOS, correct?

**Comment by wonder-sk** [comment]
@rbperezu1980 as far as I understand, Garmin GPSMAP 65S does not provide interface to work as an external GPS receiver for a phone/tablet (using NMEA protocol) - it has Bluetooth support to connect with Garmin's apps to sync waypoints, routes, background maps etc.

https://support.garmin.com/en-US/?faq=xnxBqawGRp0vickWJHl1d6

I am going to close this, but please feel free to reopen if this is not correct.
