### ISSUE TITLE
¿Es posible almacenar datos de fechas anteriores a 1900?

### ISSUE THREAD

**Issue by lefcgis** [MerginMaps/docs#533]
Buen día amigos! 🙋‍♂️🇵🇪🇧🇷

Tengo un proyecto personal donde busco recolectar información histórica, relacionada específicamente a fechas. Muchos de los datos contienen datos de años anterios a 1900 (por ejemplo: 1845, 17/05/1898, 1705, etc.). Sin embargo, no puedo hacerlo con la variable tipo DATE, ya que el mínimo valor que acepta es el de 1900.

![Image](https://github.com/user-attachments/assets/47df2beb-d7ec-4367-b531-f9bb5dd87782)

La opción que tenemos en el QGIS es esta.
![Image](https://github.com/user-attachments/assets/9ca74212-7f7b-4e6e-b700-eed46400a3d1)

En mi opinión, contar con opciones anterios a 1900 va contribuir a todos los usuarios o proyectos que busquen, por ejemplo, salvaguardar la información de patrimonio histórico cultural, arqueología, geología, arquitectura, entre otros. Quizás se pueda desarrollar un script donde se utilice solo DATETIME(MySQL), teniendo en cuenta que PostgreSQL tiene una limitación con TIMESTAMP (1901-12-14 to 2038-01-19. ).

Mi nombre es Lucho Ferrer y será un placer contribuir a que podamos encontra la mejor solución.

Muchas gracias por su tiempo,

L.

**Comment by erpas** [comment]
Thanks for reporting the problem @lefcgis 
I have create a ticket in the mobile app repository:
https://github.com/MerginMaps/mobile/issues/3693
Please follow this one to see when it is resolved.
