### ISSUE TITLE
Add notes on how to set up a custom folder for storing photos

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/docs#65]
see https://github.com/lutraconsulting/input-docs/issues/36

maybe add to https://merginmaps.com/docs/howto/project/settingup_forms_photo/

**Comment by wonder-sk** [comment]
somehow documented here: https://merginmaps.com/docs/howto/project/features/#attachment-external-resource-widget

**Comment by PeterPetrik** [comment]
e.g. https://public.cloudmergin.com/projects/input-testing/tc10_custom_photo_directory/tree

**Comment by PeterPetrik** [comment]
![Uploading Screenshot 2021-12-16 at 18.07.56.png…]()

**Comment by PeterPetrik** [comment]
<img width="569" alt="Screenshot 2021-12-16 at 18 07 56" src="https://user-images.githubusercontent.com/804608/146424344-acc6360c-2584-45dc-86a8-9e7c119b874d.png">
