### ISSUE TITLE
Update GPS external connection

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/docs#94]
existing documentatiton is misleading after merging https://github.com/lutraconsulting/input/pull/1886 and related

https://github.com/MerginMaps/docs/blob/main/src/field/external_gps.md

**Comment by tomasMizera** [comment]
#### What to add to documentation:
 - the safest way how to connect any device is:
   1. set up your device based on instructions of its manufacturer. You should continue only when you are sure that the device is working and sending data
   2. pair the device via system settings (note: it is possible to it directly via Input, but it is much easier to first go to settings on Android and pair it and then continue to Input)
   3. select the receiver in Input
 - if whatever goes wrong, make sure:
   - your bluetooth is turned on
   - your device is turned on, has battery and is sending data
   - you can try to remove the device in Input and add it again from Input

(if the device is working, uses classic bluetooth (not BLE), is discoverable during pair and feeds data, there _should_ not be any problem )

**Comment by tomasMizera** [comment]
Also, add a list of vendors that work with iOS, see discussion starting here: https://github.com/lutraconsulting/input/pull/1906#issuecomment-1023191497

**Comment by wonder-sk** [comment]
Also we can start building a database of supported devices. Currently known to work:

- **Emlid Reach RS+** - directly via bluetooth connection. Android only. It can connect to phone's hotspot and it has internal ntrip client to receive corrections. Supports 1cm accuracy with corrections.
- **Leica FLX100** - through Leica Zeno Connect app (https://play.google.com/store/apps/details?id=com.leica.zenoconnect&hl=en&gl=US) which also acts as a ntrip client and sends the corrections to the device. The app will set mock location in Android. It is also possible to connect directly via bluetooth (even multiple phones can be connected at once), but if no phone has Zeno app running, there will be no corrections available. Supports 1cm accuracy with corrections. Android only (even though zeno app is on iOS too, it's not supported, at least this device)
